### ISSUE TITLE
Web gui via https?

### ISSUE THREAD

**Issue by rbtfrog** [pfsense/docs#26]
Is there a reason why the pfsense web gui does not handle connections with https?  Wouldn't it be more secure to transmit passwords and such ove a secure channel?

**Comment by jim-p** [comment]
The GUI defaults to HTTPS. If it's running HTTP, then it has been set to HTTP since before the GUI changed defaults, or someone deliberately set it to HTTP.

However, that is not a documentation issue. This site is not for support or diagnostic discussion.

For assistance in solving problems, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).
