### ISSUE TITLE
IPsec - Authentication Method

### ISSUE THREAD

**Issue by wotu77** [pfsense/docs#45]
Missing in the "Authentication Method" field "EAP-MSChapv2". I have only: Mutal PSK and Mutal RSA.

**Comment by jim-p** [comment]
That selection is specific to mobile IPsec, and can't be used for site to site. So it's in the mobile/remote access setup documentation and not the site-to-site documentation.

**Comment by wotu77** [comment]
I don't understand. I using this https://blog.iandreev.com/?p=3617 and in section "For the second section Phase 1 Proposal (Authentication)..." is "Authentication Method" - "EAP-MSChapv2" but i have choise "Mutal PSK" or "Mutal RSA" only.

**Comment by wotu77** [comment]
I don't understand. I using this https://blog.iandreev.com/?p=3617 and in section "For the second section Phase 1 Proposal (Authentication)..." is "Authentication Method" - "EAP-MSChapv2" but i have choise "Mutal PSK" or "Mutal RSA" only.

**Comment by jim-p** [comment]
The supplied link is for a mobile (Remote Access) IPsec setup, not site-to-site. As I stated earlier, if you want to know more about EAP-MSCHAPv2, you need to look in the remote access VPN docs, not site-to-site.

This document is for site-to-site and since EAP-MSCHAPv2 cannot be used for site-to-site, it is NOT explained there:
https://www.netgate.com/docs/pfsense/vpn/ipsec/configuring-a-site-to-site-ipsec-vpn.html#phase-1

This document is for Remote Access and explains EAP-MSCHAPv2:
https://www.netgate.com/docs/pfsense/vpn/ipsec/configuring-an-ipsec-remote-access-mobile-vpn-using-ikev2-with-eap-mschapv2.html

There is nothing missing in the document/section you reported, you were on the wrong page for the type of setup you were looking for.

If you have more questions, follow up on the forum or pfSense subreddit.

**Comment by wotu77** [comment]
look this https://i1.wp.com/blog.iandreev.com/wp-content/uploads/2018/03/2018-03-05_12-02-54.png?resize=1024%2C273&ssl=1

**Comment by wotu77** [comment]
good, I understood
