### ISSUE TITLE
Feedback on Routing and Multi-WAN — Using Multiple IPv4 WAN Connections

### ISSUE THREAD

**Issue by eableson** [pfsense/docs#69]
**Page:** https://www.netgate.com/docs/pfsense/routing/multi-wan.html

**Feedback:**

I recently ran into some difficulties with a multi-wan setup that were the fallout of selecting a gateway group as the default gateway. In this situation, there is no default gateway in the routing table so any traffic that falls outside of the bounds of a policy based route definition will get a "route not found" or host unreachable result.

If I could suggest an edit, it would be to note that the default gateway should always be a physical interface in the troubleshooting section. For reference : https://forum.netgate.com/topic/138875/broken-port-forwarding

**Comment by jim-p** [comment]
Selecting a gateway group on that screen is supposed to work. If it didn't work for you, I suggest starting a forum thread at https://forum.netgate.com and gathering some info there. If there is a bug, we need more info it find it and get it fixed. There is at least one known issue at https://redmine.pfsense.org/issues/9004

The suggested edit may be true for your install/environment but only due to that issue, so it's not something we should add, we should focus on fixing the issue you are experiencing.
