### ISSUE TITLE
Feedback on VPN - OpenVPN - Configuring a Single Multi-Purpose OpenVPN Instance

### ISSUE THREAD

**Issue by fchiacchiaretta** [pfsense/docs#82]
Hi,
I configured an OpenVPN instance following this guide, and access to resources behind OpenVPN server works properly.
Main server configuration relevant snippets:

* IPv4 Tunnel Network: 10.0.0.0/24
* **Redirect IPv4 Gateway: true (not reported in the docs)**
* Topology: net30
* Avanced Configuration - Custom Options: route 10.0.1.0 255.255.255.0;

Client specific overrides have subnets like:

* 10.0.1.252/30
* 10.0.1.248/30
etc.

With this configuration, clients with overrides specified above could not access public internet resources through the tunnel, because outbound NAT automatic rule is configured for subnet 10.0.0.0/24 only; adding a static mapping for subnet 10.0.1.0/24 fixed this issue (I'm using Outbound NAT Hybrid mode).

I would be nice to add this bit of configuration to the docs, tunnelling all the traffic for roadwarrior clients is a common use case and the NAT rule can be easily forgotten.

Best,
Federico Chiacchiaretta

**Comment by jim-p** [comment]
The doc is correct as it is. If you need to check "Redirect gateway" then you did not properly define all of your "Local" networks to be pushed to clients in the overrides as stated in the doc.

**Comment by fchiacchiaretta** [comment]
I checked "Redirect gateway" because my use-case is **slightly** different than the one in the docs, not because I _did not properly define_ local networks in overrides.
"Redirect gateway" option exists and is useful indeed, so I was suggesting to add it in the docs, and also pointing out that an additional configuration is needed in this case (additional Outbound NAT mapping).

If there is something against "Redirect IPv4 Gateway" usage, or simply this particular doc isn't supposed to cover it, then this would have been a better answer than saying that I cannot configure it that way.

Great way to handle user feedback.

**Comment by jim-p** [comment]
Those suggestions go against the purpose of that document, however. It is intended to be for the specific scenario it covers. There are plenty of other examples of the other settings and how they are useful around the docs. Not every useful option needs to be mentioned in every document/how-to.

Your original comment implied there was a problem with the doc because it didn't work for you, but if your scenario doesn't match what the doc was walking you through then that isn't a problem with the documentation, you needed to adapt it to fit what you needed. That doesn't mean the document also needs to be adapted.
